/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PROJ_CRUD;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author didi
 */
public class MenuKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuKaryawan
     */
    public MenuKaryawan() {
        initComponents();
        tampil_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama_user = new javax.swing.JTextField();
        alamat_user = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Menu Karyawan");

        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "ID", "Nama", "Alamat"
            }
        ));
        tabel_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_karyawan);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        alamat_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kota", "Jakarta", "Bandung", "Yogyakarta", "Cirebon", "Aceh" }));

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BERSIH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UBAH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        id_user.setEditable(false);

        jLabel3.setText("ID");

        jButton4.setText("HAPUS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_user)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(id_user)
                            .addComponent(alamat_user, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(alamat_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nm = nama_user.getText();
        String Kota = (String) alamat_user.getSelectedItem();
        
        if(Nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Nama Terlebih Dahulu");
        }else if(Kota.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulu");
        }else{
            try{
                String Q = "INSERT INTO karyawan (nama, alamat) VALUES ('"+Nm+"', '"+Kota+"')";
                java.sql.Connection Vconn = (Connection)KoneksiDB.konfigDB(); //memanggil fungsi
                java.sql.PreparedStatement s = Vconn.prepareStatement(Q);
                s.execute();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Tambah Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_table();
        bersih();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawanMouseClicked
        // TODO add your handling code here:
        // Menampilkan data kedalam form pengisian:
        int baris = tabel_karyawan.rowAtPoint(evt.getPoint());
        //int kolom = tabel_karyawan.columnAtPoint(evt.getPoint());
        
        String id = tabel_karyawan.getValueAt(baris, 1).toString();
        id_user.setText(id);
        
        String nm = tabel_karyawan.getValueAt(baris, 2).toString();
        nama_user.setText(nm);
        
        String addrs = tabel_karyawan.getValueAt(baris, 3).toString();
        alamat_user.setSelectedItem(addrs);
        
    }//GEN-LAST:event_tabel_karyawanMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = id_user.getText();
        String nm = nama_user.getText();
        String almt = (String) alamat_user.getSelectedItem();
        
        if(nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Nama Terlebih Dahulu");
        }else if(almt.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulu");
        }else{
            try{
                String Vsql = "UPDATE karyawan SET id = '"+id+"', nama = '"+nm+"', alamat = '"+almt+"' WHERE id = '"+id+"'";
                Connection Vconn = (Connection)KoneksiDB.konfigDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement(Vsql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Ubah Data Berhasil");
                tampil_table();
                bersih();
            }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ubah Data Gagal");
            JOptionPane.showMessageDialog(this, e.getMessage());   
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = id_user.getText();
        String nm = nama_user.getText();
        String almt = (String) alamat_user.getSelectedItem();
        
        if(nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Nama Terlebih Dahulu");
        }else if(almt.equals("Pilih Kota")){
            JOptionPane.showMessageDialog(null, "Pilih Alamat Terlebih Dahulu");
        }else{
                try {
                    // 1. Query
                    String query = "DELETE FROM karyawan WHERE id = '"+id+"'";
                    // 2. Koneksi
                    Connection Vconn = (Connection)KoneksiDB.konfigDB(); //memanggil fungsi 
                    // 3. Statement
                    java.sql.PreparedStatement stm = Vconn.prepareStatement(query);
                    // 4. Eksekusi Query
                    stm.execute();
                    // 5. Menampilkan Notifikasi
                    JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
                    tampil_table();
                    bersih();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hapus Data Gagal");
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampil_table()
    {
        //membuat objek model pada tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No");
        tb.addColumn("ID");
        tb.addColumn("Nama");
        tb.addColumn("Alamat");
        
        try{
            int counter = 1;
            // 1. Query
            String query = "SELECT * FROM karyawan";
            
            // 2. Fungsi koneksi
            java.sql.Connection vconn = (Connection)KoneksiDB.konfigDB();
            
            // 3. Kirim Parameter fungsi Java ke SQL
            java.sql.Statement s = vconn.createStatement();
            
            // 4. Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            // 5. Looping
            while(r.next()){
                tb.addRow(new Object[]{
                    counter++,r.getString(1), r.getString(2), r.getString(3)
                });
                
            }
            tabel_karyawan.setModel(tb);
        }catch (Exception e){
            
        }
        
    }
    
    private void bersih(){
        id_user.setText("");
        nama_user.setText("");
        alamat_user.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alamat_user;
    private javax.swing.JTextField id_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_user;
    private javax.swing.JTable tabel_karyawan;
    // End of variables declaration//GEN-END:variables
}
